server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql:///blue_corner
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: aiying2002

mybatis:
  configuration:
    map-underscore-to-camel-case: true

