server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql:///blue_corner
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: aiying2002

redis:
  host: 101.42.1.15
  port: 6379
  password: 123456
  database: 0
  lettuce:
    pool:
      max-idle: 16
      max-active: 32
      min-idle: 8

mybatis:
  configuration:
    map-underscore-to-camel-case: true